/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData community = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData jobs = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData health = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData environment = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData civicEngagement = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData education = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData income = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData housing = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData workLifeBalance = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData safety = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData lifeSatisfaction = const IconData(0xe814, fontFamily: _kFontFam);
}
